export const CART_LOADING = 'CART_LOADING';  //LOAD_CURRENT_ITEM
export const CART_QUANTITY = 'CART_QUANTITY';
export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';